

POST http://localhost:5000/query
Content-Type: application/json

{"query": "create database test;"}

###

POST http://localhost:5000/query
Content-Type: application/json

{"query": "create table test.test(id int, name varchar(100))"}

###
POST http://localhost:5000/query
Content-Type: application/json

{"query": "insert into test.test values (3, \"monda\")"}


###
PUT http://localhost:5000/test/test
Content-Type: application/json

{"id": 13,"name": "producto"}

###
PATCH  http://localhost:5000/test/test/13
Content-Type: application/json

{"name": "funciona"}

###
DELETE   http://localhost:5000/test/test/13

###

POST http://localhost:5000/query
Content-Type: application/json

{"query": "select * from test.test"}

###

GET  http://localhost:5000/test/test


###

POST http://localhost:5000/query
Content-Type: application/json

{"query": "drop database test;"}


###

POST http://localhost:5000/query
Content-Type: application/json

{"query": "desc test.test;"}